import { useMemo } from "react";
import { Link } from "react-router-dom";
import StateBlock from "../components/StateBlock";
import ImpactCard from "../components/ImpactCard";
import { BudgetMeter, CarbonMeter, EquityMeter } from "../components/BudgetMeter";
import type { UseScenario } from "../state/useScenario";
import { narrate } from "../engine/narrate";

export default function Impact({ scenario }: { scenario: UseScenario }) {
  const { dataset, report, loading, error } = scenario;

  const paragraph = useMemo(() => (report ? narrate(report) : ""), [report]);
  const carbonById = useMemo(() => {
    const m = new Map<string, any>();
    if (report) for (const c of report.carbon.services) m.set(c.serviceId, c);
    return m;
  }, [report]);

  return (
    <StateBlock loading={loading} error={error}>
      {dataset && report && (
        <div className="grid gap-6">
          {/* The narrated paragraph is the single most important thing on this
              view, so it sits first — above the fold, before the meters. The
              h1 is deliberately compact for the same reason. */}
          <section
            className="card bg-gradient-to-br from-slate-50 to-white"
            aria-labelledby="impact-heading"
          >
            <h1
              id="impact-heading"
              className="text-xs uppercase tracking-wide text-accent font-semibold"
            >
              Plain-language explanation
            </h1>
            {/* aria-live: the paragraph is recomputed whenever the allocation
                changes, so AT users are told rather than left to discover it. */}
            <p
              className="mt-2 text-lg leading-relaxed text-ink"
              aria-live="polite"
              aria-atomic="true"
            >
              {paragraph}
            </p>
            <p className="mt-3 text-xs text-slate-500">
              This paragraph is <strong>computed</strong> from your allocation, not
              generated by a language model — it can't hallucinate. Same numbers,
              same words. Every time.
            </p>
          </section>

          <section aria-labelledby="totals-heading">
            <h2 id="totals-heading" className="sr-only">
              Budget, equity, and emissions totals
            </h2>
            <div className="grid sm:grid-cols-3 gap-4">
              <BudgetMeter
                totalAllocated={report.totalAllocated}
                totalBudget={report.totalBudget}
                overBudget={report.overBudget}
              />
              <EquityMeter
                score={report.equity.score}
                baselineScore={report.equity.baselineScore}
                delta={report.equity.delta}
              />
              <CarbonMeter
                baselineTonnes={report.carbon.baselineTonnes}
                projectedTonnes={report.carbon.projectedTonnes}
                deltaTonnes={report.carbon.deltaTonnes}
              />
            </div>
          </section>

          <div className="flex flex-wrap gap-2">
            <Link to="/allocate" className="btn">
              <span aria-hidden="true">← </span>Back to allocator
            </Link>
            <Link to="/compare" className="btn">
              Compare scenarios
            </Link>
          </div>

          <section aria-labelledby="per-service-heading">
            <h2 id="per-service-heading" className="text-lg font-semibold text-ink mb-3">
              Per-service impact
            </h2>
            <div className="grid md:grid-cols-2 gap-4">
              {report.services.map((s) => (
                <ImpactCard key={s.serviceId} service={s} carbon={carbonById.get(s.serviceId)} />
              ))}
            </div>
          </section>
        </div>
      )}
    </StateBlock>
  );
}
