import { useMemo } from "react";
import { Link } from "react-router-dom";
import StateBlock from "../components/StateBlock";
import ImpactCard from "../components/ImpactCard";
import { BudgetMeter, CarbonMeter, EquityMeter } from "../components/BudgetMeter";
import type { UseScenario } from "../state/useScenario";
import { narrate } from "../engine/narrate";

export default function Impact({ scenario }: { scenario: UseScenario }) {
  const { dataset, report, loading, error } = scenario;

  const paragraph = useMemo(() => (report ? narrate(report) : ""), [report]);
  const carbonById = useMemo(() => {
    const m = new Map<string, any>();
    if (report) for (const c of report.carbon.services) m.set(c.serviceId, c);
    return m;
  }, [report]);

  return (
    <StateBlock loading={loading} error={error}>
      {dataset && report && (
        <div className="grid gap-6">
          <section className="card bg-gradient-to-br from-slate-50 to-white">
            <div className="text-xs uppercase tracking-wide text-accent font-semibold">
              Plain-language explanation
            </div>
            <p className="mt-2 text-lg leading-relaxed text-ink">{paragraph}</p>
            <p className="mt-3 text-xs text-slate-500">
              This paragraph is <strong>computed</strong> from your allocation, not generated by a language model —
              it can't hallucinate. Same numbers, same words. Every time.
            </p>
          </section>

          <div className="grid sm:grid-cols-3 gap-4">
            <BudgetMeter
              totalAllocated={report.totalAllocated}
              totalBudget={report.totalBudget}
              overBudget={report.overBudget}
            />
            <EquityMeter
              score={report.equity.score}
              baselineScore={report.equity.baselineScore}
              delta={report.equity.delta}
            />
            <CarbonMeter
              baselineTonnes={report.carbon.baselineTonnes}
              projectedTonnes={report.carbon.projectedTonnes}
              deltaTonnes={report.carbon.deltaTonnes}
            />
          </div>

          <div className="flex flex-wrap gap-2">
            <Link to="/allocate" className="btn">← Back to allocator</Link>
            <Link to="/compare" className="btn">Compare scenarios</Link>
          </div>

          <div className="grid md:grid-cols-2 gap-4">
            {report.services.map((s) => (
              <ImpactCard key={s.serviceId} service={s} carbon={carbonById.get(s.serviceId)} />
            ))}
          </div>
        </div>
      )}
    </StateBlock>
  );
}
