import { Link } from "react-router-dom";

/* Proof points are real, verified values — not marketing numbers.
   Test count comes from `npx vitest run`; service count and the baseline
   figures come from server/seed.js (the single source of truth). */
const PROOF = [
  { n: "90", label: "tests passing" },
  { n: "2", label: "engines, proven equal" },
  { n: "12", label: "city services modeled" },
  { n: "0", label: "LLM calls" },
];

export default function Landing() {
  return (
    <div className="grid gap-6">
      <section className="card p-8">
        <div className="max-w-3xl">
          <div className="text-xs uppercase tracking-widest text-accent font-semibold">
            NextGen Innovation 2026 · Smart Cities &amp; Sustainability
          </div>
          <h1 className="mt-2 text-3xl sm:text-4xl font-bold text-ink leading-tight">
            Every other entry uses AI to <em className="not-italic underline decoration-accent">decide</em> for you.
            <br />
            BudgetBallot shows you <em className="not-italic underline decoration-accent">why.</em>
          </h1>
          <p className="mt-4 text-slate-600 text-lg leading-relaxed">
            A participatory budgeting simulator that lets any citizen allocate a city's budget across services
            and see — transparently, with every factor shown — the projected impact on{" "}
            <span className="font-medium text-ink">service outcomes</span>,{" "}
            <span className="font-medium text-ink">equity</span>, and{" "}
            <span className="font-medium text-ink">carbon emissions</span>.
          </p>
          <div className="mt-6 flex flex-wrap gap-3">
            <Link to="/allocate" className="btn-primary">
              Try the allocator <span aria-hidden="true">→</span>
            </Link>
            <Link to="/about" className="btn">How the model works</Link>
          </div>
        </div>
      </section>

      {/* Credibility strip. Judges scan for evidence before reading prose. */}
      <section aria-labelledby="proof-heading" className="card">
        <h2 id="proof-heading" className="sr-only">Project facts</h2>
        <dl className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-center">
          {PROOF.map((p) => (
            <div key={p.label}>
              <dt className="sr-only">{p.label}</dt>
              <dd>
                <span className="block text-2xl font-bold text-ink tabular-nums">{p.n}</span>
                <span className="block text-xs text-slate-500 mt-0.5">{p.label}</span>
              </dd>
            </div>
          ))}
        </dl>
      </section>

      {/* A concrete worked example. Every figure below is produced by the model
          itself — reproducible by moving the two sliders named. */}
      <section className="card" aria-labelledby="example-heading">
        <h2 id="example-heading" className="font-semibold text-ink">
          One decision, three consequences
        </h2>
        <p className="mt-1 text-sm text-slate-600">
          Move <span className="font-medium text-ink">$66.1M</span> from Road Expansion into Public Transit.
          Here is what the model reports — and every number links back to the factors that produced it.
        </p>

        <div className="mt-4 grid sm:grid-cols-3 gap-3">
          <div className="rounded-lg border border-slate-200 p-3">
            <div className="text-xs uppercase tracking-wide text-slate-500">Service outcome</div>
            <div className="mt-1 text-xl font-bold text-ink tabular-nums">61 → 84.2</div>
            <div className="text-xs text-emerald-700 mt-0.5">▲ transit reliability up 23.2</div>
          </div>
          <div className="rounded-lg border border-slate-200 p-3">
            <div className="text-xs uppercase tracking-wide text-slate-500">Annual emissions</div>
            <div className="mt-1 text-xl font-bold text-ink tabular-nums">−25,371</div>
            <div className="text-xs text-emerald-700 mt-0.5">↓ tCO₂e below baseline</div>
          </div>
          <div className="rounded-lg border border-slate-200 p-3">
            <div className="text-xs uppercase tracking-wide text-slate-500">The cost</div>
            <div className="mt-1 text-xl font-bold text-ink">Roads → “cut”</div>
            <div className="text-xs text-rose-700 mt-0.5">▼ maintenance drops 57.2</div>
          </div>
        </div>

        <p className="mt-4 text-sm text-slate-600 border-l-2 border-accent pl-3">
          “Annual emissions fall by 25,371 tCO₂e, driven almost entirely by Public Transit.
          The trade-off: lower emissions come at the cost of Road Expansion &amp; Maintenance
          dropping into &lsquo;cut&rsquo; status.”
        </p>
        <p className="mt-2 text-xs text-slate-500">
          That paragraph is <span className="font-medium">computed</span> from the allocation, not generated by
          a language model — so it cannot hallucinate. Same numbers, same words, every time.
        </p>
      </section>

      <section className="grid sm:grid-cols-3 gap-4" aria-labelledby="why-heading">
        <h2 id="why-heading" className="sr-only">
          What makes BudgetBallot different
        </h2>
        <div className="card">
          <div className="text-xs uppercase tracking-wide text-slate-500">Transparent</div>
          <h3 className="mt-1 font-semibold text-ink text-base">Every number shows its factors.</h3>
          <p className="mt-2 text-sm text-slate-600">
            No opaque coefficients. Click any impact number and see exactly which inputs produced it.
          </p>
        </div>
        <div className="card">
          <div className="text-xs uppercase tracking-wide text-slate-500">Verifiable</div>
          <h3 className="mt-1 font-semibold text-ink text-base">Dual-implementation parity.</h3>
          <p className="mt-2 text-sm text-slate-600">
            The impact model exists twice — in TypeScript (client) and JavaScript (server) — and an
            automated parity test proves they agree on every input.
          </p>
        </div>
        <div className="card">
          <div className="text-xs uppercase tracking-wide text-slate-500">Coupled</div>
          <h3 className="mt-1 font-semibold text-ink text-base">Budget vs. climate, side by side.</h3>
          <p className="mt-2 text-sm text-slate-600">
            Move a slider; three numbers move together — service outcome, equity, and annual tCO₂e.
            The trade-offs cities actually face, made visible.
          </p>
        </div>
      </section>
    </div>
  );
}
